### ISSUE TITLE
add instructions for `gomobile build`

### ISSUE THREAD

**Issue by rakyll** [rakyll/drummachine#2]

**Comment by joeblew99** [comment]
+1 Instructions would be very helpful since this stuff is pretty new.

**Comment by rakyll** [comment]
Please follow the instructions from http://godoc.org/golang.org/x/mobile/example/basic. Once you have gomobile installed and inited, you can run 

```
$ go get -d github.com/rakyll/drummachine
$ gomobile install github.com/rakyll/drummachine
```

I will try to update the docs later in the day.
