### ISSUE TITLE
[suggestion] move current dev to a separate branch

### ISSUE THREAD

**Issue by odeke-em** [rakyll/drummachine#5]
Could we move the current re-write to a new branch (until it is complete) and then revert the old functioning prototype to master?
This is because users will be building the test app and the first prototype seems functional + interactivie enough that it could retain attention, as opposed to waiting till the latest re-write is done :)
Please let me know what you think.

**Comment by rakyll** [comment]
Too late, the new drum machine records and plays back now. Have fun!

**Comment by odeke-em** [comment]
Cool, thanks! I'll check it out.
